---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
#  - ansible # Installed via Pip.
  - git
  - gpg
  - httpie
  - iperf
  - nmap
  - ssh-copy-id
  - openssl
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - slack
  - visual-studio
  - brave-browser
  - cyberduck
  - notion
  - vmware-fusion
  - iterm2
  - microsoft-office
  - logitech-presentation
  - app-cleaner
  - istat-menus
  - atom
  - whatsapp
  - signal
  - little-snitch
  - gitkraken


# See `geerlingguy.mas` role documentation for usage instructions.
# mas_installed_apps: []
mas_email: ""
mas_password: ""
mas_signin_dialog: false # do I need this?

mas_installed_apps:
    - { id: 441258766, name: "Magnet" }
    - { id: 1274495053, name: "Microsoft To Do"}
    - { id: 1410709951, name: "Smart Countdown Timer"}

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
